env:
  global:
    - ROCK_NAME=watchdog

jobs:
  include:
    - script:
      - make -f .travis.mk
    - stage: deploy
      name: Publish rockspecs
      script: skip
      deploy:
        - provider: script
          script: curl --fail -X PUT -F rockspec=@$ROCK_NAME-scm-2.rockspec
            https://$ROCKS_USERNAME:$ROCKS_PASSWORD@rocks.tarantool.org
        - on:
            tags: true
          provider: script
          script: cat $ROCK_NAME-scm-2.rockspec |
            sed -E
            -e "s/branch = '.+'/tag = '$TRAVIS_TAG'/g"
            -e "s/version = '.+'/version = '$TRAVIS_TAG-1'/g" |
            curl --fail -X PUT -F "rockspec=@-;filename=$ROCK_NAME-$TRAVIS_TAG-1.rockspec"
            https://$ROCKS_USERNAME:$ROCKS_PASSWORD@rocks.tarantool.org
